name: "Traceability GitHub Action"
author: "Daniel Leaver"
description: "Ensures git commit messages contain a Trello short link"
inputs:
  noid_verification_strategy:
    required: false
    default: "upper_case"
    description: "One of any_case, upper_case, lower_case, never."
  commit_verification_strategy:
    required: false
    default: "all_commits"
    description: "One of all_commits, never."
  title_verification_strategy:
    required: false
    default: "always"
    description: "One of always, never."
  trello_api_key:
    required: true
    description: "API key for Trello. Use GitHub secrets. Don't use plaintext."
  trello_api_token:
    required: true
    description: "API token for Trello. Use GitHub secrets. Don't use plaintext."
  github_access_token:
    required: true
    description: "API token for GitHub. Use GitHub secrets. Don't use plaintext."
runs:
  using: "node12"
  main: "dist/index.js"